from .certification import Certification
from .cv import CV
from .education import Education
from .experience import Experience
from .language import Language
from .person_detail import PersonDetail
from .skill import Skill
from .social import Social
from .technology import Technology
