---

image: python:3.7

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

stages:
    - check-reqs
    - linter
    - test

poetry-check:
    stage: check-reqs
    before_script:
      - pip install poetry
    script:
      - poetry check
    tags:
      - shared

flake8:
    stage: linter
    before_script:
      - python -m venv venv
      - source venv/bin/activate
      - pip install poetry
      - poetry install
    script:
      - flake8
    tags:
      - shared

unit-tests:
    stage: test
    before_script:
      - python -m venv venv
      - source venv/bin/activate
      - pip install poetry
      - poetry install
    script:
      - invoke test
    tags:
      - shared
